config/routes.rb
Rails.application.routes.draw do
  resources :seccion_tomaestado_ruta
  resources :ruta_medidors
  resources :medidors
  resources :clientes
  resources :ruta
  resources :tomaestados
  resources :seccions
  devise_for :users, :controllers => { :registrations => "users/registrations" }  
  resources :subestacions
  get 'index/index'

  root 'index#index'

       get 'index' => 'index#index'
       post '/ruta/store_route' => 'ruta#store_route'
       post '/medidors/store_medidor' => 'medidors#store_medidor'

  devise_scope :user do
    get "users", to: "users/registrations#index"
  end

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	def to_s
		"(#{self.dni}) #{self.apellido}, #{self.nombre}"
	end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Se ha creado un nuevo Cliente.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Se ha actualizado el Cliente.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Se ha eliminado el Cliente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:dni, :apellido, :nombre, :telefono, :email, :domicilio)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @cliente.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h4>
      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :dni, "DNI", class: "col-sm-1 control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :dni, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :apellido, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :apellido, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nombre, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :nombre, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telefono, "Teléfono", class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :telefono, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :domicilio, class: "col-sm-1 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :domicilio, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <%= f.submit value: "Guardar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @cliente, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editando cliente</h4>
</div>

<%= render 'form' %>

app/views/clientes/index.html.erb
<div class="page-header">
  <%= link_to new_cliente_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nuevo cliente
  <% end %>
  <h4>Listado de clientes</h4>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>DNI</th>
      <th>Apellido</th>
      <th>Nombre</th>
      <th>Teléfono</th>
      <th>Email</th>
      <th>Domicilio</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.dni %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.domicilio %></td>
        <td style="width: 100px;">
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Acciones
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to 'Ver', cliente %></li>
              <li><%= link_to 'Editar', edit_cliente_path(cliente) %></li>
              <li><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Estás seguro?' } %></li>
            </ul>          
          </div>
        </td>                
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clientes/new.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nuevo cliente</h4>
</div>

<%= render 'form' %>

app/views/clientes/show.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_cliente_path(@cliente), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Cliente</h4>
</div>

<dl class="dl-horizontal">
  <dt>DNI:</dt>
  <dd><%= @cliente.dni %></dd>

  <dt>Apellido:</dt>
  <dd><%= @cliente.apellido %></dd>

  <dt>Nombre:</dt>
  <dd><%= @cliente.nombre %></dd>

  <dt>Telefono:</dt>
  <dd><%= @cliente.telefono %></dd>

  <dt>Email:</dt>
  <dd><%= @cliente.email %></dd>

  <dt>Domicilio:</dt>
  <dd><%= @cliente.domicilio %></dd>
</dl>