config/routes.rb
Rails.application.routes.draw do
  resources :seccion_tomaestado_ruta
  resources :ruta_medidors
  resources :medidors
  resources :clientes
  resources :ruta
  resources :tomaestados
  resources :seccions
  devise_for :users, :controllers => { :registrations => "users/registrations" }  
  resources :subestacions
  get 'index/index'

  root 'index#index'

       get 'index' => 'index#index'
       post '/ruta/store_route' => 'ruta#store_route'
       post '/medidors/store_medidor' => 'medidors#store_medidor'

  devise_scope :user do
    get "users", to: "users/registrations#index"
  end

end

app/models/ruta_medidor.rb
class RutaMedidor < ActiveRecord::Base
  belongs_to :rutum
  belongs_to :medidor
end

app/controllers/ruta_medidors_controller.rb
class RutaMedidorsController < ApplicationController
  before_action :set_ruta_medidor, only: [:show, :edit, :update, :destroy]

  # GET /ruta_medidors
  # GET /ruta_medidors.json
  def index
    @ruta_medidors = RutaMedidor.all
  end

  # GET /ruta_medidors/1
  # GET /ruta_medidors/1.json
  def show
  end

  # GET /ruta_medidors/new
  def new
    @ruta_medidor = RutaMedidor.new
  end

  # GET /ruta_medidors/1/edit
  def edit
  end

  # POST /ruta_medidors
  # POST /ruta_medidors.json
  def create
    @ruta_medidor = RutaMedidor.new(ruta_medidor_params)

    respond_to do |format|
      if @ruta_medidor.save
        format.html { redirect_to @ruta_medidor, notice: 'Ruta medidor was successfully created.' }
        format.json { render :show, status: :created, location: @ruta_medidor }
      else
        format.html { render :new }
        format.json { render json: @ruta_medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruta_medidors/1
  # PATCH/PUT /ruta_medidors/1.json
  def update
    respond_to do |format|
      if @ruta_medidor.update(ruta_medidor_params)
        format.html { redirect_to @ruta_medidor, notice: 'Ruta medidor was successfully updated.' }
        format.json { render :show, status: :ok, location: @ruta_medidor }
      else
        format.html { render :edit }
        format.json { render json: @ruta_medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruta_medidors/1
  # DELETE /ruta_medidors/1.json
  def destroy
    @ruta_medidor.destroy
    respond_to do |format|
      format.html { redirect_to ruta_medidors_url, notice: 'Ruta medidor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruta_medidor
      @ruta_medidor = RutaMedidor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ruta_medidor_params
      params.require(:ruta_medidor).permit(:rutum_id, :medidor_id)
    end
end

app/helpers/ruta_medidors_helper.rb
module RutaMedidorsHelper
end

app/views/ruta_medidors/_form.html.erb
<%= form_for(@ruta_medidor, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @ruta_medidor.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@ruta_medidor.errors.count, "error") %> prohibited this ruta_medidor from being saved:</h4>

      <ul>
      <% @ruta_medidor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rutum_id, "Ruta", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.collection_select :rutum_id, Rutum.all, :id, :to_s, {prompt: false}, {:class => "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :medidor_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.collection_select :medidor_id, Medidor.all, :id, :to_s, {prompt: false}, {:class => "form-control"} %>
    </div>
  </div>  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :value => "Guardar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/ruta_medidors/edit.html.erb
<div class="page-header">
  <%= link_to ruta_medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @ruta_medidor, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editando ruta_medidor</h4>
</div>

<%= render 'form' %>

app/views/ruta_medidors/index.html.erb
<div class="page-header">
  <%= link_to new_ruta_medidor_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nueva ruta_medidor
  <% end %>
  <h4>Listado de ruta_medidors</h4>
</div>


  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Ruta</th>
        <th>Medidor</th>
        <th>&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @ruta_medidors) do |ruta_medidor| %>
        <td><%= ruta_medidor.rutum %></td>
        <td><%= ruta_medidor.medidor %></td>
        <td style="width: 100px;">
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Acciones
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to 'Ver', ruta_medidor %></li>
              <li><%= link_to 'Editar', edit_ruta_medidor_path(ruta_medidor) %></li>
              <li><%= link_to 'Eliminar', ruta_medidor, method: :delete, data: { confirm: 'Estás seguro?' } %></li>
            </ul>          
          </div>
        </td>                
      <% end %>
    </tbody>
  </table>

app/views/ruta_medidors/new.html.erb
<div class="page-header">
  <%= link_to ruta_medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nuevo ruta_medidor</h4>
</div>

<%= render 'form' %>

app/views/ruta_medidors/show.html.erb
<div class="page-header">
  <%= link_to ruta_medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_ruta_medidor_path(@ruta_medidor), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Ver ruta_medidor</h4>
</div>

<dl class="dl-horizontal">
  <dt>Ruta:</dt>
  <dd><%= @ruta_medidor.rutum %></dd>

  <dt>Medidor:</dt>
  <dd><%= @ruta_medidor.medidor %></dd>

</dl>