config/routes.rb
Rails.application.routes.draw do
  resources :seccion_tomaestado_ruta
  resources :ruta_medidors
  resources :medidors
  resources :clientes
  resources :ruta
  resources :tomaestados
  resources :seccions
  devise_for :users, :controllers => { :registrations => "users/registrations" }  
  resources :subestacions
  get 'index/index'

  root 'index#index'

       get 'index' => 'index#index'
       post '/ruta/store_route' => 'ruta#store_route'
       post '/medidors/store_medidor' => 'medidors#store_medidor'

  devise_scope :user do
    get "users", to: "users/registrations#index"
  end

end

app/models/medidor.rb
class Medidor < ActiveRecord::Base
  belongs_to :cliente

  def to_s
	self.nombre
  end
end

app/controllers/medidors_controller.rb
require 'json'

class MedidorsController < ApplicationController
  before_action :set_medidor, only: [:show, :edit, :update, :destroy]

  # GET /medidors
  # GET /medidors.json
  def index
    @medidors = Medidor.all
  end

  # GET /medidors/1
  # GET /medidors/1.json
  def show
    @medidor = Medidor.find(params[:id])

    @geojson = Array.new
    @geojson << {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [@medidor.longitud, @medidor.latitud]
      },
      properties: {
        title: @medidor.nombre,
        description: Cliente.find(@medidor.cliente_id).domicilio,
        name: @medidor.nombre,
        address: Cliente.find(@medidor.cliente_id).domicilio,
        :'marker-color' => '#00607d',
        :'marker-symbol' => 'circle-stroked',
        :'marker-size' => 'medium'
      }
    }
  end

  # GET /medidors/new
  def new
    @medidor = Medidor.new
  end

  # GET /medidors/1/edit
  def edit
    @medidor = Medidor.find(params[:id])

    @geojson = Array.new
    @geojson << {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [@medidor.longitud, @medidor.latitud]
      },
      properties: {
        title: @medidor.nombre,
        description: Cliente.find(@medidor.cliente_id).domicilio,
        name: @medidor.nombre,
        address: Cliente.find(@medidor.cliente_id).domicilio,
        :'marker-color' => '#00607d',
        :'marker-symbol' => 'circle-stroked',
        :'marker-size' => 'medium'
      }
    }
  end

  # POST /medidors
  # POST /medidors.json
  def create
    @medidor = Medidor.new(medidor_params)

    respond_to do |format|
      if @medidor.save
        format.html { redirect_to @medidor, notice: 'Se ha creado un nuevo Medidor.' }
        format.json { render :show, status: :created, location: @medidor }
      else
        format.html { render :new }
        format.json { render json: @medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medidors/1
  # PATCH/PUT /medidors/1.json
  def update
    respond_to do |format|
      if @medidor.update(medidor_params)
        format.html { redirect_to @medidor, notice: 'Se ha actualizado el Medidor.' }
        format.json { render :show, status: :ok, location: @medidor }
      else
        format.html { render :edit }
        format.json { render json: @medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medidors/1
  # DELETE /medidors/1.json
  def destroy
    @medidor.destroy
    respond_to do |format|
      format.html { redirect_to medidors_url, notice: 'Se ha eliminado el Medidor.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medidor
      @medidor = Medidor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medidor_params
      params.require(:medidor).permit(:numero, :nombre, :novedades, :novedades_criticas, :latitud, :longitud, :cliente_id)
    end
end

app/helpers/medidors_helper.rb
module MedidorsHelper
end

app/views/medidors/_form.html.erb
<div id='map-medidor'>
</div>
<br/>

<%= form_for(@medidor, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @medidor.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@medidor.errors.count, "error") %> prohibited this medidor from being saved:</h4>
      <ul>
      <% @medidor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :numero, "Número", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :numero, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nombre, class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :nombre, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :novedades, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :novedades, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :novedades_criticas, "Novedades críticas", class: "col-sm-2 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :novedades_criticas, class: "form-control" %>
    </div>
  </div>
  <%= hidden_field(:medidor, :latitud) %>
  <%= hidden_field(:medidor, :longitud) %>
  <div class="form-group">
    <%= f.label :cliente_id, "Cliente", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.collection_select :cliente_id, Cliente.all, :id, :to_s, {prompt: false}, {:class => "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit value: "Guardar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<script>
  $(document).on('page:load', function() {    
    L.mapbox.accessToken = 'pk.eyJ1IjoibWFydGluY2hvIiwiYSI6ImZlMTY1MzUwMjQ5MGQ3YjgyY2NkYTU2MzJiZWIyMWRiIn0.Yhwbui6KvzC0JziPkwWXuQ';
    var map = L.mapbox.map('map-medidor', 'martincho.nb477913');
    map.on('click', function(e) {
        // Let's add a callback to makeMarker so that it can draw the route only
        // *after* it's done processing the marker adding.
        makeMarker(e);
    });

    var markers = [];

    <% if @geojson %>
      L.mapbox.featureLayer().setGeoJSON(<%= raw @geojson.to_json %>).addTo(map);
      //markers.push();
    <% end %>

    //Function that makes a Marker
    function makeMarker(e) {
      if (markers.length > 0) return;
      var marker = L.marker(e.latlng, { 
        draggable: true
        })
      .bindPopup("<input type='button' value='Eliminar marcador' id='boton_eliminar' class='btn btn-primary'/>")
      .addTo(map);
      marker.on("popupopen", onPopupOpen);
      markers.push(marker);
      var latlng = marker._latlng;
      $('#medidor_latitud').val(latlng.lat);
      $('#medidor_longitud').val(latlng.lng);
      //document.getElementById('medidor_latitud').value = latlng.lat;
      //document.getElementById('medidor_longitud').value = latlng.lng;
      console.log('latitud: '+document.getElementById('medidor_latitud').value+ 'longitud: '+document.getElementById('medidor_longitud').value);
      //$.post('/medidors/store_medidor',medidor);  
    }
    // Function to handle delete as well as other events on marker popup open
    function onPopupOpen() {
      var tempMarker = this;
      // To remove marker on click of delete
      $("#boton_eliminar:visible").click(function () {
          $('#medidor_latitud').val('');
          $('#medidor_longitud').val('');
          map.removeLayer(tempMarker);
          markers.pop();
      });
    }

  });
</script>

app/views/medidors/edit.html.erb
<div class="page-header">
  <%= link_to medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @medidor, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editando medidor</h4>
</div>

<%= render 'form' %>

app/views/medidors/index.html.erb
<div class="page-header">
  <%= link_to new_medidor_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nuevo medidor
  <% end %>
  <h4>Listado de medidores</h4>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Número</th>
      <th>Nombre</th>
      <th>Novedades</th>
      <th>Novedades críticas</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Cliente</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @medidors.each do |medidor| %>
      <tr>
        <td><%= medidor.numero %></td>
        <td><%= medidor.nombre %></td>
        <td><%= medidor.novedades %></td>
        <td><%= medidor.novedades_criticas %></td>
        <td><%= medidor.latitud %></td>
        <td><%= medidor.longitud %></td>
        <td><%= medidor.cliente %></td>
        <td style="width: 100px;">
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Acciones
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to 'Ver', medidor %></li>
              <li><%= link_to 'Editar', edit_medidor_path(medidor) %></li>
              <li><%= link_to 'Eliminar', medidor, method: :delete, data: { confirm: 'Estás seguro?' } %></li>
            </ul>          
          </div>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/medidors/new.html.erb
<div class="page-header">
  <%= link_to medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nuevo medidor</h4>
</div>

<%= render 'form' %>

app/views/medidors/show.html.erb
<div class="page-header">
  <%= link_to medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_medidor_path(@medidor), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Medidor</h4>
</div>

<div id="medidor-show"></div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>Datos del medidor</strong></div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Número:</dt>
      <dd><%= @medidor.numero %></dd>

      <dt>Nombre:</dt>
      <dd><%= @medidor.nombre %></dd>

      <dt>Novedades:</dt>
      <dd><%= @medidor.novedades %></dd>

      <dt>Novedades críticas:</dt>
      <dd><%= @medidor.novedades_criticas %></dd>

      <dt>Latitud:</dt>
      <dd><%= @medidor.latitud %></dd>

      <dt>Longitud:</dt>
      <dd><%= @medidor.longitud %></dd>

      <dt>Cliente:</dt>
      <dd><%= @medidor.cliente %></dd>
    </dl>
  </div>
</div>

<script>
  $(document).on('page:load', function() {
    L.mapbox.accessToken = 'pk.eyJ1IjoibWFydGluY2hvIiwiYSI6ImZlMTY1MzUwMjQ5MGQ3YjgyY2NkYTU2MzJiZWIyMWRiIn0.Yhwbui6KvzC0JziPkwWXuQ';
    var userMap = L.mapbox.map('medidor-show', 'martincho.nb477913');
    L.mapbox.featureLayer().setGeoJSON(<%= raw @geojson.to_json %>).addTo(userMap);
  });
</script>