config/routes.rb
Rails.application.routes.draw do
  resources :seccion_tomaestado_ruta
  resources :ruta_medidors
  resources :medidors
  resources :clientes
  resources :ruta
  resources :tomaestados
  resources :seccions
  devise_for :users, :controllers => { :registrations => "users/registrations" }  
  resources :subestacions
  get 'index/index'

  root 'index#index'

       get 'index' => 'index#index'
       post '/ruta/store_route' => 'ruta#store_route'
       post '/medidors/store_medidor' => 'medidors#store_medidor'

  devise_scope :user do
    get "users", to: "users/registrations#index"
  end

end

app/models/ability.rb
class Ability
    include CanCan::Ability 

    def initialize( user ) 
        user ||= User.new                          # guest user 

        if user.role :super_admin 
            can :manage, :all 
        elsif user.role :product_admin 
            can :manage, [ Product, Asset, Issue ] 
        elsif user.role :product_team 
            can :read, [ Product, Asset ] 
            # manage products, assets he owns 
            can :manage, Product do | product | 
            product.try( :owner ) == user
        end 
            can :manage, Asset do | asset | 
                asset.assetable.try( :owner ) == user
            end 
        end 
    end 
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	def to_s
		"(#{self.dni}) #{self.apellido}, #{self.nombre}"
	end
end

app/models/medidor.rb
class Medidor < ActiveRecord::Base
  belongs_to :cliente

  def to_s
	self.nombre
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/ruta_medidor.rb
class RutaMedidor < ActiveRecord::Base
  belongs_to :rutum
  belongs_to :medidor
end

app/models/rutum.rb
class Rutum < ActiveRecord::Base
  def to_s
	self.nombre
  end
end

app/models/seccion.rb
class Seccion < ActiveRecord::Base
  belongs_to :subestacion

  def to_s
	"#{self.nombre}, (#{Subestacion.find(self.subestacion_id).to_s})"
  end
end

app/models/subestacion.rb
class Subestacion < ActiveRecord::Base
	def to_s
		self.nombre
	end
end

app/models/tomaestado.rb
class Tomaestado < ActiveRecord::Base
  belongs_to :user

  def to_s
	"(#{self.dni}) - #{self.apellido}, #{self.nombre}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :roles 

  def role( role ) 
    !roles.find_by_name( role.to_s.camelize ).nil?
  end 

  def to_s
  	self.email
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/ruta_controller.rb
class RutaController < ApplicationController
  before_action :set_rutum, only: [:show, :edit, :update, :destroy]

  # GET /ruta
  # GET /ruta.json
  def index
    @ruta = Rutum.all
  end

  def store_route     
    session[:ruta] = params[:ruta]
    render :nothing => true
  end

  # GET /ruta/1
  # GET /ruta/1.json
  def show
    @medidor_ids = RutaMedidor.where(:rutum_id => params[:id]).ids
    @medidores = Medidor.find(@medidor_ids)
    
    @geojson = Array.new
    @medidores.each do |medidor|
      @geojson << {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [medidor.longitud, medidor.latitud]
        },
        properties: {
          title: medidor.nombre,
          description: Cliente.find(medidor.cliente_id).domicilio,
          name: medidor.nombre,
          address: Cliente.find(medidor.cliente_id).domicilio,
          :'marker-color' => '#00607d',
          :'marker-symbol' => 'circle-stroked',
          :'marker-size' => 'medium'
        }
      }
    end
  end

  # GET /ruta/new
  def new
    @rutum = Rutum.new
  end

  # GET /ruta/1/edit
  def edit
  end

  # POST /ruta
  # POST /ruta.json
  def create

    rutum_params[:ruta] = session[:ruta]    
    debugger
    @rutum = Rutum.new(rutum_params)
    ruta_medidor_params[:ruta_id] = @rutum.id
    
    @ruta_medidor = new RutaMedidor(ruta_medidor_params)
    
    respond_to do |format|
      if @rutum.save
        format.html { redirect_to @rutum, notice: 'Se ha creado una nueva Ruta.' }
        format.json { render :show, status: :created, location: @rutum }
      else
        format.html { render :new }
        format.json { render json: @rutum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruta/1
  # PATCH/PUT /ruta/1.json
  def update
    rutum_params[:ruta] = session[:ruta]    
    respond_to do |format|
      if @rutum.update(rutum_params)
        format.html { redirect_to @rutum, notice: 'Se ha actualizado la Ruta.' }
        format.json { render :show, status: :ok, location: @rutum }
      else
        format.html { render :edit }
        format.json { render json: @rutum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruta/1
  # DELETE /ruta/1.json
  def destroy
    @rutum.destroy
    respond_to do |format|
      format.html { redirect_to ruta_url, notice: 'Se ha eliminado la Ruta.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rutum
      @rutum = Rutum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rutum_params
      params.require(:rutum).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/medidors_helper.rb
module MedidorsHelper
end

app/helpers/ruta_helper.rb
module RutaHelper
end

app/helpers/seccions_helper.rb
module SeccionsHelper
end

app/helpers/subestacions_helper.rb
module SubestacionsHelper
end

app/helpers/tomaestados_helper.rb
module TomaestadosHelper
end

app/views/index/index.html.erb
<div class="page-header"><h4>Inicio</h4></div>

<div class="alert alert-info" role="alert">Sistema de control de toma estados :D</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Sistema de Gestión de Medidores</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Esto debería quitarse -->
  <script src='https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.js'></script>
  <script src='https://api.mapbox.com/mapbox.js/plugins/mapbox-directions.js/v0.4.0/mapbox.directions.js'></script>
  <link rel='stylesheet' href='https://api.mapbox.com/mapbox.js/plugins/mapbox-directions.js/v0.4.0/mapbox.directions.css' type='text/css' />
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Sistema de Gestión de Medidores", index_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li class="<%= 'active' if params[:controller] == 'index' %>"><%= link_to "Inicio", index_path %>
              <li class="<%= 'active' if params[:controller] == 'subestacions' %>"><%= link_to "Subestaciones", subestacions_path %>
              <li class="<%= 'active' if params[:controller] == 'seccions' %>"><%= link_to "Secciones", seccions_path %>
              <li class="<%= 'active' if params[:controller] == 'tomaestados' %>"><%= link_to "Tomaestados", tomaestados_path %>
              <li class="<%= 'active' if params[:controller] == 'ruta' %>"><%= link_to "Rutas", ruta_path %>
              <li class="<%= 'active' if params[:controller] == 'clientes' %>"><%= link_to "Clientes", clientes_path %>
              <li class="<%= 'active' if params[:controller] == 'medidors' %>"><%= link_to "Medidores", medidors_path %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  <strong><%= current_user.email %></strong>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">                
                  <li class="dropdown-header">Cuenta</li>
                  <li><%= link_to 'Editar cuenta', edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Administración</li>
                  <li>
                    <%= link_to 'Administrar usuarios', users_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == "alert" ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <%= msg %>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
  <footer class="footer">
      <div class="container">
        <p class="text-muted">Sistema de Gestión de Medidores.</p>
      </div>
  </footer>
</body>
</html>